name: Docker Image Security Scan with Dockle

on:
  push:
    branches:
      - main  # Or any other branch you'd like to scan
  pull_request:
    branches:
      - main  # Or any other branch you'd like to scan

jobs:
  scan:
    name: Docker Security Scan with Dockle
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Run Dockle security scan using the Dockle Action and save output to dockle.json
      - name: Run Dockle security scan
        id: dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: 'rameshlodh/frontend:a983e03e387f6e603f15016179b562ecd338bb31'  # Replace with your image name
          format: 'json'  # Store the output in JSON format for better readability and parsing
          output: 'dockle-json'
          exit-code: '1'  # Exit code to return if vulnerabilities are found (non-zero will fail the job)
          exit-level: 'warn'  # Fail the job if vulnerabilities of 'warn' level or higher are found
          # ignore: 'CIS-DI-0001,DKL-DI-0006'  # Ignore specific rule IDs
        continue-on-error: true  # Allows the job to continue even if Dockle finds vulnerabilities

      # Step 6: Upload the artifact
      - name: Upload Dockle Scan Results as Artifact
        uses: actions/upload-artifact@v3
        if: always()  # Always run this step regardless of the job's outcome
        with:
          name: dockle-scan-results  # Artifact name
          path: dockle-json  # Path to the Dockle scan results file
          # if-no-files-found: warn  # Warn if no files are found
          # include-hidden-files: false
