name: Docker Image Security Scan with Dockle

on:
  push:
    branches:
      - main  # Or any other branch you'd like to scan
  pull_request:
    branches:
      - main  # Or any other branch you'd like to scan

jobs:
  scan:
    name: Docker Security Scan with Dockle
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Run Dockle security scan using the Dockle Action
      - name: Run Dockle security scan
        uses: goodwithtech/dockle-action@main
        with:
          image: 'rameshlodh/frontend:a983e03e387f6e603f15016179b562ecd338bb31'  
          format: 'json'
          exit-code: '0' 
          exit-level: 'high'
          # ignore: 'CIS-DI-0001,DKL-DI-0006'
